Make script/pull work with the latest opt.yml move.

diff --git a/script/pull b/script/pull
--- a/script/pull
+++ b/script/pull
@@ -6,6 +6,7 @@
 [ "$DEBUG" ] && set -x
 root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
 . $root/vendor/script/helpers
+yml=$root/script/yml
 set -e
 
 pull() {
@@ -20,42 +21,24 @@ cd $root
 if [ $# -eq 1 ]; then
   parse_repository "$1"
   if [ -d "dockerfiles/$repo" ]; then
-    cd "dockerfiles/$repo"
-    parse_repository "$1"
-    
+    cd "dockerfiles/$repo"; parse_repository "$1"
     if [ -x script/pull ]; then script/pull $tag
-    elif [ -f options/tags ] && [ "$tag" ]; then
-      if grep -qE "^$tag/" options/tags; then
-        pull $current_user/$repo:$tag
-      else
-        >&2 printf "Unable to find the tag %s\n" "$tag"
-        exit 1
-      fi
+    elif [ "$tag" = "latest" ]; then pull $current_user/$repo:$tag
+    elif ([ "$tag" ] && [ -f opts.yml ] && $yml -R tags && $yml -V $tag tags) || \
+         ([ "$tag" ] && [ -d tags ] && [ -d "tags/$tag" ]); then
+      pull $current_user/$repo:$tag
 
-    elif [ -f options/tags ]; then
-      for v in $(cat options/tags); do
-        pull "$current_user/$repo:$(echo $v | awk -F/ '{
-          print $1
-        }')"
+    elif [ "$tag" ]; then
+      >&2 printf "Unable to find the tag '%s'\n" "$tag"
+      exit 1
+
+    elif [ -f opts.yml ] && $yml -R tags; then
+      for v in $($yml -k tags); do
+        pull $current_user/$repo:$v
       done
-
-    elif [ -d tags ] && [ "$tag" ]; then
-      if [ -d "tags/$tag" ]; then
-        pull "$current_user/$repo:$tag"
-      else
-        >&2 printf "Unknown tag '%s'" $tag
-        exit 1
-      fi
-
-    elif [ -d tags ]; then
-      for v in tags/*; do
-        pull "$current_user/$repo:$(
-          basename $v
-        )"
-      done
-
     else
-      pull "$current_user/$repo:${tag:-latest}"
+      tag=${tag:-latest}
+      pull $current_user/$repo:$tag
     fi
   else
     >&2 echo "Unknown repository"
